version: '{build}'

image: Visual Studio 2013

before_build:
  - ps: '[xml]$prod = Get-Content .\prod_src\packages\gui.prepost\data\definition.xml'
  - ps: '[xml]$dev = Get-Content .\dev_src\packages\gui.prepost\data\definition.xml'
  - ps: '[xml]$yasu = Get-Content .\yasu_src\packages\gui.prepost\data\definition.xml'
  - ps: $Env:PROD_SHA1=$prod.GuiDefinition.'github-sha1'.Substring(0,8)
  - ps: $Env:DEV_SHA1=$dev.GuiDefinition.'github-sha1'.Substring(0,8)
  - ps: $Env:YASU_SHA1=$yasu.GuiDefinition.'github-sha1'.Substring(0,8)

build_script:
  - C:\Qt\Tools\QtInstallerFramework\2.0\bin\binarycreator --offline-only -c prod_src/config/config.xml -p prod_src/packages iRIC_Offline_Installer_prod-%PROD_SHA1%.exe
  - C:\Qt\Tools\QtInstallerFramework\2.0\bin\binarycreator --offline-only -c dev_src/config/config.xml  -p dev_src/packages  iRIC_Offline_Installer_dev-%DEV_SHA1%.exe
  - C:\Qt\Tools\QtInstallerFramework\2.0\bin\binarycreator --offline-only -c yasu_src/config/config.xml -p yasu_src/packages iRIC_Offline_Installer_yasu-%YASU_SHA1%.exe
  # build versions with no runtime libraries
  - rd /s /q prod_src\packages\runtime
  - rd /s /q dev_src\packages\runtime
  - rd /s /q yasu_src\packages\runtime
  - C:\Qt\Tools\QtInstallerFramework\2.0\bin\binarycreator --offline-only -c prod_src/config/config.xml -p prod_src/packages iRIC_Offline_Installer_No_Runtime_prod-%PROD_SHA1%.exe
  - C:\Qt\Tools\QtInstallerFramework\2.0\bin\binarycreator --offline-only -c dev_src/config/config.xml  -p dev_src/packages  iRIC_Offline_Installer_No_Runtime_dev-%DEV_SHA1%.exe
  - C:\Qt\Tools\QtInstallerFramework\2.0\bin\binarycreator --offline-only -c yasu_src/config/config.xml -p yasu_src/packages iRIC_Offline_Installer_No_Runtime_yasu-%YASU_SHA1%.exe

artifacts:
  - path: iRIC_Offline_Installer_prod-$(PROD_SHA1).exe
  - path: iRIC_Offline_Installer_dev-$(DEV_SHA1).exe
  - path: iRIC_Offline_Installer_yasu-$(YASU_SHA1).exe
  - path: iRIC_Offline_Installer_No_Runtime_prod-$(PROD_SHA1).exe
  - path: iRIC_Offline_Installer_No_Runtime_dev-$(DEV_SHA1).exe
  - path: iRIC_Offline_Installer_No_Runtime_yasu-$(YASU_SHA1).exe
