function Component()
{}

Component.prototype.createOperationsForArchive = function(archive)
{
	component.addOperation("Extract", archive, "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312");
}

Component.prototype.createOperations = function()
{
	component.createOperations();

	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/accessible")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/accessible/qtaccessiblewidgets.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/accessible/qtaccessiblewidgets.dll")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/bearer")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/bearer/qgenericbearer.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/bearer/qgenericbearer.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/bearer/qnativewifibearer.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/bearer/qnativewifibearer.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/cgnsdll.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/cgnsdll.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/expat.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/expat.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/ffmpeg.exe", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/ffmpeg.exe")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/gdal111.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/gdal111.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/gdalwarp.exe", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/gdalwarp.exe")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/geos.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/geos.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/hdf5.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/hdf5.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/hdf5_hl.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/hdf5_hl.dll")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/iconengines")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/iconengines/qsvgicon.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/iconengines/qsvgicon.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/icudt54.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/icudt54.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/icuin54.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/icuin54.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/icuuc54.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/icuuc54.dll")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qdds.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qdds.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qgif.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qgif.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qicns.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qicns.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qico.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qico.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qjp2.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qjp2.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qjpeg.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qjpeg.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qmng.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qmng.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qsvg.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qsvg.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qtga.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qtga.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qtiff.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qtiff.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qwbmp.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qwbmp.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/imageformats/qwebp.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/imageformats/qwebp.dll")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/languages")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/languages/qtbase_ja_JP.qm", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/languages/qtbase_ja_JP.qm")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/languages/qt_es_ES.qm", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/languages/qt_es_ES.qm")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/languages/qt_ja_JP.qm", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/languages/qt_ja_JP.qm")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/libeay32.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/libeay32.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/libEGL.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/libEGL.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/libGLESV2.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/libGLESV2.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/libifcoremd.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/libifcoremd.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/libifportmd.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/libifportmd.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/libiomp5md.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/libiomp5md.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/libmmd.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/libmmd.dll")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/bzip2.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/bzip2.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/fontconfig.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/fontconfig.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/freetype.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/freetype.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/frei0r.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/frei0r.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/gnutls.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/gnutls.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/lame.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/lame.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libass.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libass.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libbluray.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libbluray.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libcaca.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libcaca.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libgsm.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libgsm.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libiconv.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libiconv.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libilbc.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libilbc.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libmodplug.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libmodplug.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libtheora.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libtheora.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libvorbis.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libvorbis.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/libvpx.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/libvpx.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/opencore-amr.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/opencore-amr.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/openjpeg.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/openjpeg.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/opus.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/opus.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/rtmpdump.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/rtmpdump.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/schroedinger.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/schroedinger.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/soxr.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/soxr.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/speex.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/speex.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/twolame.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/twolame.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/vid.stab.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/vid.stab.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/vo-aacenc.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/vo-aacenc.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/vo-amrwbenc.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/vo-amrwbenc.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/wavpack.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/wavpack.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/x264.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/x264.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/xavs.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/xavs.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/xvid.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/xvid.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/licenses/zlib.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/licenses/zlib.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/README.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/README.txt")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/ffmpeg/README_ffmpeg.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/ffmpeg/README_ffmpeg.txt")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/mlitx2nc")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/mlitx2nc/LICENSE", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/mlitx2nc/LICENSE")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/mlitx2nc/LICENSE.ja-utf8", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/mlitx2nc/LICENSE.ja-utf8")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/mlitx2nc/README.txt", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/mlitx2nc/README.txt")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/triangle")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/licenses/triangle/README", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/licenses/triangle/README")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/mlitx2nc.exe", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/mlitx2nc.exe")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/msvcr100.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/msvcr100.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/netcdf.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/netcdf.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/opengl32sw.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/opengl32sw.dll")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/platforms")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/platforms/qwindows.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/platforms/qwindows.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/proj.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/proj.dll")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/pythonmodule")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/pythonmodule/iric.py", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/pythonmodule/iric.py")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/pythonmodule/_iric.pyd", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/pythonmodule/_iric.pyd")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Core.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Core.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Gui.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Gui.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Multimedia.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Multimedia.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5MultimediaWidgets.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5MultimediaWidgets.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Network.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Network.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5OpenGL.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5OpenGL.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Positioning.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Positioning.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5PrintSupport.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5PrintSupport.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Qml.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Qml.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Quick.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Quick.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Sensors.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Sensors.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Sql.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Sql.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Svg.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Svg.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5WebChannel.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5WebChannel.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5WebEngine.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5WebEngine.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5WebEngineCore.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5WebEngineCore.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5WebEngineWidgets.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5WebEngineWidgets.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5WebKit.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5WebKit.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5WebKitWidgets.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5WebKitWidgets.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Widgets.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Widgets.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/Qt5Xml.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/Qt5Xml.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/qwt.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/qwt.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/shapelib.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/shapelib.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/ssleay32.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/ssleay32.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/svml_dispmd.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/svml_dispmd.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/szip.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/szip.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/triangle.exe", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/triangle.exe")
	component.addOperation("Mkdir", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/udunits")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/udunits/udunits2-accepted.xml", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/udunits/udunits2-accepted.xml")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/udunits/udunits2-base.xml", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/udunits/udunits2-base.xml")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/udunits/udunits2-common.xml", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/udunits/udunits2-common.xml")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/udunits/udunits2-derived.xml", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/udunits/udunits2-derived.xml")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/udunits/udunits2-prefixes.xml", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/udunits/udunits2-prefixes.xml")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/udunits/udunits2.xml", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/udunits/udunits2.xml")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/udunits2.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/udunits2.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/unzip.exe", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/unzip.exe")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkalglib-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkalglib-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkCommonComputationalGeometry-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkCommonComputationalGeometry-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkCommonCore-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkCommonCore-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkCommonDataModel-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkCommonDataModel-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkCommonExecutionModel-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkCommonExecutionModel-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkCommonMath-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkCommonMath-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkCommonMisc-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkCommonMisc-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkCommonSystem-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkCommonSystem-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkCommonTransforms-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkCommonTransforms-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkDICOMParser-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkDICOMParser-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersCore-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersCore-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersExtraction-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersExtraction-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersFlowPaths-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersFlowPaths-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersGeneral-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersGeneral-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersGeometry-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersGeometry-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersHybrid-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersHybrid-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersModeling-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersModeling-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersSources-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersSources-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersStatistics-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersStatistics-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkFiltersTexture-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkFiltersTexture-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkfreetype-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkfreetype-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkftgl-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkftgl-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkgl2ps-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkgl2ps-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkGUISupportQt-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkGUISupportQt-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkImagingColor-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkImagingColor-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkImagingCore-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkImagingCore-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkImagingFourier-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkImagingFourier-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkImagingGeneral-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkImagingGeneral-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkImagingHybrid-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkImagingHybrid-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkImagingSources-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkImagingSources-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkInteractionStyle-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkInteractionStyle-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkInteractionWidgets-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkInteractionWidgets-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkIOCore-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkIOCore-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkIOExport-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkIOExport-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkIOGeometry-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkIOGeometry-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkIOImage-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkIOImage-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkIOLegacy-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkIOLegacy-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkjpeg-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkjpeg-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkjsoncpp-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkjsoncpp-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkmetaio-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkmetaio-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkpng-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkpng-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingAnnotation-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingAnnotation-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingContext2D-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingContext2D-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingCore-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingCore-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingFreeType-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingFreeType-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingFreeTypeOpenGL-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingFreeTypeOpenGL-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingGL2PS-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingGL2PS-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingLabel-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingLabel-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingLOD-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingLOD-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingOpenGL-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingOpenGL-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingQt-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingQt-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkRenderingVolume-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkRenderingVolume-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtksys-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtksys-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtktiff-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtktiff-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/vtkzlib-6.1.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/vtkzlib-6.1.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/yaml-cpp.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/yaml-cpp.dll")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/zip.exe", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/zip.exe")
	component.addOperation("Copy", "@TargetDir@/guis/prepost_archive_v3/runtime/zlib.dll", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/zlib.dll")

	component.addOperation("CreateShortcut", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/iRIC.exe",
		"@StartMenuDir@/iRIC_3.0.19.6312.lnk", "workingDirectory=@TargetDir@/guis/prepost_archive_v3/3.0.19.6312");
	component.addOperation("CreateShortcut", "@TargetDir@/guis/prepost_archive_v3/3.0.19.6312/iRIC.exe",
		"@DesktopDir@/iRIC_3.0.19.6312.lnk", "workingDirectory=@TargetDir@/guis/prepost_archive_v3/3.0.19.6312");
}
